spring:
  application:
    name: authentication-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 0
server:
  port: 8081

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.jlau.scoresystem.model
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8848/eureka

