
spring:
  redis:
    database: 0
    port: 6379
    host: localhost
    jedis:
      pool:
        max-idle: 20
        max-active: 20
    timeout: 3000
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      batch-size: 16355
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: defaultConsumerGroup
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      max-poll-records: 100
    listener:
      missing-topics-fatal: false
      type: batch
